# Generated by Django 4.2 on 2023-04-21 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coupon",
            old_name="acitve",
            new_name="active",
        ),
    ]
